### ISSUE TITLE
deposit_redeemScript's OP_2DROP

### ISSUE THREAD

**Issue by PierreRochard** [petertodd/checklocktimeverify-demos#1]
Might be a dumb question, but why is deposit_redeemScript "self.expiry_nlocktime, 1, OP_NOP2, OP_2DROP" instead of "self.expiry_nlocktime, OP_NOP2, OP_DROP"? In other words, what effect does the 1 have?

**Comment by petertodd** [comment]
Oh, the 1 sets the right side when the if statement executes. If you wanted to redeem via the other side, you'd have a 0 in the scriptSig in that place.

**Comment by petertodd** [comment]
(Sorry for the late reply; scaling bitcoin conf...)
